[package]
authors = ["Sparkenstein <zetabytes.pp@gmail.com>"]
edition = "2018"
name = "binrs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.1"
nanoid = "0.3.0"
rocket = "0.4.7"
serde = {version = "1.0", features = ["derive"]}

[dependencies.rocket_contrib]
default-features = false
features = ["handlebars_templates"]
version = "0.4.7"
